name: On Push Run

on:
  pull_request:
    types: [opened]
jobs:
  hello-world:
    name: Hello world
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Check-out main repository
      uses: actions/checkout@v2
      
    - name: Hello World
      run: python .github/workflows/auto_close_prs.py
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: sh