name: Localization CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - name: Install yamllint
        run: sudo apt-get install -y yamllint
      - name: Run yamllint
        run: yamllint .

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install flake8
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 flake8-bugbear
      - name: Run flake8
        run: python3 -m flake8
